language: python
dist: xenial

notifications:
  email: false

python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"

env:
  jobs:
    - ICU_VERSION="65.1"
    - ICU_VERSION="64.2"
    - ICU_VERSION="63.2"
    - ICU_VERSION="62.2"
    - ICU_VERSION="61.2"
    - ICU_VERSION="60.3"
    - ICU_VERSION="59.2"
    - ICU_VERSION="58.3"
    - ICU_VERSION="57.2"
    - ICU_VERSION="56.2"
    - ICU_VERSION="55.2"
    - ICU_VERSION="54.2"
    - ICU_VERSION="53.2"
    - ICU_VERSION="52.2"
    - ICU_VERSION="51.3"
    - ICU_VERSION="50.2"
  # The "global" environment variables are defined for each job.
  global:
    - PYICU_LIBRARIES="icui18n:icuuc:icudata"
    - PYICU_INCLUDES="/tmp/icu4c/include"
    - PYICU_LFLAGS="-L/tmp/icu4c/lib"

cache:
  ccache: true
  pip: true
  timeout: 1000
  directories:
    - /tmp/icu4c

before_install:
  # install ICU4C from source
  - mkdir -p /tmp/icu4c
  - export ICU_URL="https://github.com/unicode-org/icu/releases/download/release-${ICU_VERSION/./-}/icu4c-${ICU_VERSION/./_}-src.tgz"
  - wget -nv -O /tmp/icu4c/icu4c.tgz "$ICU_URL"
  - tar -xzf /tmp/icu4c/icu4c.tgz -C /tmp/icu4c
  - pushd /tmp/icu4c/icu/source && ./configure --prefix=/tmp/icu4c && make && make install && popd

install:
  - pip install . pytest

script:
  - LD_LIBRARY_PATH="/tmp/icu4c/lib" py.test
